version: '3.5'

services:
    frontend:
      build: ./frontend
      ports:
        - "3000:3000"
    backend:
      build: ./backend
      ports:
        - "5000:5000"
      volumes: 
        - ./training/model:/src/model
    training:
      build: ./training
      volumes:
        - ./training/imgs:/src/imgs
        - ./training/model:/src/model
