version: '3.5'

services:
  redis:
      image: redis
      restart: unless-stopped
      ports:
        - "6379:6379"
  db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=admin
        - PGPASSWORD=admin
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
 
  proxy:
      image: nginx
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
       - 80:80
      restart: unless-stopped
      depends_on:
       - backend
       - frontend
 
  frontend:
      build: ./frontend
      expose:
        - "5000"
      ports:
        - "5000:5000"
      environment: 
        - API_URL=http://localhost:8000
      container_name: frontend-docker
      depends_on:
        - backend

  backend:
      build: ./backend
      links:
        - redis
        - db
      expose:
        - "8000"
      ports:
        - "8000:8000"
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=admin
        - DB_PASSWORD=admin
        - DB_HOST=db
      container_name: backend-docker
