version: '3.5'


services:
  redis:
      image: redis
      ports:
        - "6379:6379"

  frontend:
      build: ./frontend
      expose:
        - "5000"
      ports:
        - "5000:5000"
      environment: 
        - API_URL=http://localhost:8000
      container_name: frontend
      depends_on:
        - backend

  backend:
      build: ./backend
      links: 
        - redis
      expose:
        - "8000"
      ports:
        - "8000:8000"
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
      container_name: backend

